name: build-package
on: [push]
jobs:
  build-natives:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install development files for Lua 5.2 
        run: sudo apt install --no-install-recommends lua5.2 liblua5.2-dev
      - name: Build prosody native utils (hashes.c)
        run: |
          cd prosody/util-src
          sh configure
          make
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: prosody-native-utils-amd64
          path: |
            prosody/util-src/hashes.so
  build-django-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python venv
        run: |
          sudo apt install libmysqlclient-dev
          cd meet-accountmanager
          python3 -m venv venv
          . venv/bin/activate
          venv/bin/pip install wheel
          venv/bin/pip install -r requirements.txt
      - name: Copy the files to static2
        run: |
          cd meet-accountmanager
          venv/bin/python3 manage.py collectstatic 
      - name: Create archive
        run: |
          tar -cJf meet-accountmanager.tar.xz meet-accountmanager
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: meet-accountmanager
          path: meet-accountmanager.tar.xz
      - name: Create a pre Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          body: This is a prerelease.
          with_files: |
            meet-accountmanager.tar.xz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }}


